import colors from '../../assets/colors';
import {
  ScaledSheet,
  moderateScale,
  scale,
} from 'react-native-size-matters/extend';

export const styles = ScaledSheet.create({
  logoContainer: {
    flexDirection: 'row',
    marginStart: scale(16),
    alignItems: 'center',
  },
  logoHeading: {
    marginStart: scale(12),
    fontSize: moderateScale(10),
    color: colors.gray,
    fontWeight: '300',
  },
  logoSubHeading: {
    marginStart: scale(12),
    fontSize: moderateScale(16),
    color: colors.black,
    fontWeight: '400',
  },
  profileBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    marginEnd: scale(16),
  },
  profileImageContainer: {
    width: scale(32),
    height: scale(32),
    borderRadius: scale(16),
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  profileImage: {
    width: scale(32),
    height: scale(32),
  },
  headerContainer: {
    flexDirection: 'row',
    paddingHorizontal: scale(20),
    alignItems: 'center',
    paddingTop: scale(26),
    paddingBottom: scale(5),
    justifyContent: 'space-between',
    backgroundColor: colors.white,
  },
  title: {
    fontSize: moderateScale(16),
    color: colors.gray,
    fontWeight: '500',
    flex: 1,
  },
  heading: {
    fontSize: scale(16),
    color: colors.black,
    fontWeight: '400',
    marginBottom: scale(16),
  },
  reportText: {
    fontSize: moderateScale(16),
    color: colors.primary,
    fontWeight: '400',
    marginStart: scale(8),
  },
  reportIcon: {
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    width: scale(24),
    height: scale(24),
  },
  insightsContainer: {
    paddingHorizontal: scale(16),
    backgroundColor: colors.white,
  },
  numberTxt: {
    fontSize: moderateScale(40),
    color: colors.text,
    fontWeight: '700',
    marginEnd: scale(8),
  },
  rateContainer: {
    flexDirection: 'row',
    backgroundColor: colors.rateBg,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 48,
    padding: scale(8),
    maxWidth: scale(200),
  },
  rateText: {
    color: colors.rateText,
    marginStart: scale(8),
    fontSize: moderateScale(12),
    fontWeight: '600',
  },
  attendanceText: {
    fontSize: moderateScale(12),
    fontWeight: '400',
    color: colors.gray,
    marginTop: scale(10),
  },
  graphStyle: {
    paddingVertical: scale(24),
    marginBottom: scale(16),
    alignSelf: 'center',
    paddingHorizontal: scale(20),
    backgroundColor: colors.white,
  },
  actionsContainer: {
    backgroundColor: colors.white,
    paddingTop: scale(24),
    paddingHorizontal: scale(16),
    paddingBottom: scale(25),
    flex: 1,
  },
  actionsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: scale(8),
    justifyContent: 'center',
  },
  listStyle: {
    alignSelf: 'center',
    paddingVertical: scale(10),
  },
  itemContainer: {
    width: scale(180),
    height: scale(180),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    backgroundColor: colors.offWhite,
    marginHorizontal: scale(10),
    padding: scale(5),
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 5,
  },
  itemText: {
    fontSize: moderateScale(18),
    textAlign: 'center',
    lineHeight: scale(24),
    color: colors.black,
  },
});
