import {StyleSheet} from 'react-native';
import colors from '../../assets/colors';

export const styles = StyleSheet.create({
  logoContainer: {
    flexDirection: 'row',
    marginStart: 16,
    alignItems: 'center',
  },
  logoHeading: {
    marginStart: 12,
    fontSize: 10,
    color: colors.gray,
    fontWeight: '300',
  },
  logoSubHeading: {
    marginStart: 12,
    fontSize: 16,
    color: colors.black,
    fontWeight: '400',
  },
  profileBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    marginEnd: 16,
  },
  profileImageContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  profileImage: {
    width: 32,
    height: 32,
  },
  headerContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    alignItems: 'center',
    paddingTop: 26,
    paddingBottom: 5,
    justifyContent: 'space-between',
    backgroundColor: colors.white,
  },
  title: {
    fontSize: 16,
    color: colors.gray,
    fontWeight: '500',
    flex: 1,
  },
  heading: {
    fontSize: 16,
    color: colors.black,
    fontWeight: '400',
    marginBottom: 16,
  },
  reportText: {
    fontSize: 16,
    color: colors.primary,
    fontWeight: '400',
    marginStart: 8,
  },
  reportIcon: {
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    width: 24,
    height: 24,
  },
  insightsContainer: {
    paddingHorizontal: 16,
    backgroundColor: colors.white,
  },
  numberTxt: {
    fontSize: 40,
    color: colors.text,
    fontWeight: '700',
    marginEnd: 8,
  },
  rateContainer: {
    flexDirection: 'row',
    backgroundColor: colors.rateBg,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 48,
    padding: 8,
    maxWidth: 200,
  },
  rateText: {
    color: colors.rateText,
    marginStart: 8,
    fontSize: 12,
    fontWeight: '600',
  },
  attendanceText: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.gray,
    marginTop: 10,
  },
  graphStyle: {
    paddingVertical: 24,
    marginBottom: 16,
    alignSelf: 'center',
    paddingHorizontal: 20,
    backgroundColor: colors.white,
  },
  actionsContainer: {
    backgroundColor: colors.white,
    paddingTop: 24,
    paddingHorizontal: 16,
    paddingBottom: 25,
    flex: 1,
  },
  actionsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  listStyle: {
    alignSelf: 'center',
    paddingVertical: 10,
  },
  itemContainer: {
    width: 180,
    height: 180,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    backgroundColor: colors.offWhite,
    marginHorizontal: 10,
    padding: 5,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 5,
  },
  itemText: {
    fontSize: 18,
    textAlign: 'center',
    lineHeight: 24,
    color: colors.black,
  },
});
